// Photos of the site. Files and sizes are generated by
// scripts/images/photos.py (public/images/ + lib/images.json): change the
// script, then run it, never edit the files by hand.
// Alt texts and captions are in messages/*.json (home.photos.<name>).
import manifest from "./images.json";

export type PhotoName = keyof typeof manifest;

export interface Photo {
  /** Largest file; also the fallback for browsers without srcset. */
  src: string;
  /** Intrinsic size of `src`: gives the <img> its aspect ratio (no layout shift). */
  width: number;
  height: number;
  /** All widths ("…-700.webp 700w, …"), or undefined when there is only one. */
  srcSet?: string;
}

/**
 * <img> attributes of a photo. `width` is also the most CSS pixels the photo
 * may be displayed at: the files are never upscaled, so wider looks blurry.
 */
export function photo(name: PhotoName): Photo {
  const variants = manifest[name];
  const largest = variants[variants.length - 1];
  return {
    src: largest.src,
    width: largest.width,
    height: largest.height,
    srcSet: variants.length > 1 ? variants.map((v) => `${v.src} ${v.width}w`).join(", ") : undefined,
  };
}

// The kitchen gallery, in display order (captions are numbered from 02: the
// hero photo is 01). All are 4:3 crops of the same size class, so the
// gallery is a uniform grid.
export const KITCHEN_PHOTOS = ["huevoroto", "anchoa", "ternera", "chuleton", "alcachofa", "brownie"] as const satisfies readonly PhotoName[];
