// Facts about the restaurant: the ONE place where they are written.
// The page (header, hero, "Horario y contacto", footer), the metadata, the
// sitemap and the schema.org JSON-LD all read from here, so the phone number
// or the opening hours can never disagree between what people see and what
// Google reads. When a fact changes, change it here AND in the Google
// Business Profile.
import type { AppPathname, Locale } from "@/i18n/routing";
import { photo } from "./images";

// Canonical origin, no trailing slash. A hard-coded constant on purpose: an
// env variable that is missing at build time silently produces URLs like
// "undefined/aviso-legal" in the sitemap (this happened on a real project).
// www: the host the previous site was indexed under (keep it, see
// docs/MIGRATION.md).
export const SITE_URL = "https://www.elgaleondealcorcon.com";

export const SITE_NAME = "El Galeón de Alcorcón";

// Default image for link previews (WhatsApp, Facebook, X...): 1200x630, < 300 KB.
// Generated by scripts/images/brand.py.
export const DEFAULT_OG_IMAGE = "/og-default.jpg";

// Pages that search engines should index (internal paths, see
// i18n/routing.ts). The sitemap is built from this list. Pages with noindex
// (the legal pages) must NOT be here.
export const INDEXED_PATHS = ["/"] as const satisfies readonly AppPathname[];

// External services the restaurant uses. Every link to them opens in a new
// tab (target="_blank" rel="noopener").
export const LINKS = {
  /** TheFork booking widget. */
  reservations: "https://widget.thefork.com/09377b58-b595-4176-9fd8-123ac8888fa1",
  /** The menu ("carta"), hosted by NordQR so the restaurant can update it itself. */
  menu: "https://go.nordqr.com/rochedelasislas/",
  instagram: "https://www.instagram.com/elgaleondealcorcon",
  /** Google Maps place of the restaurant (the same link the previous site used). */
  maps: "https://www.google.com/maps/place/El+Gale%C3%B3n+de+Alcorc%C3%B3n/@40.3484819,-3.8416774,16z/data=!4m6!3m5!1s0xd418eb8afd1d17f:0xe64ac5bafb82b8b8!8m2!3d40.3467086!4d-3.8397318!16s%2Fg%2F1tfs2ccf?entry=ttu&g_ep=EgoyMDI1MDYyMy4yIKXMDSoASAFQAw%3D%3D",
} as const;

export const INSTAGRAM_HANDLE = "@elgaleondealcorcon";

// Organization behind the site (schema.org Organization, home page).
export const organization = {
  name: SITE_NAME,
  // Raster of at least 112x112 px, as Google requires for logos.
  logo: "/logo.png",
  sameAs: [LINKS.instagram] as string[],
};

const DAY_KEYS = ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"] as const;
export type DayKey = (typeof DAY_KEYS)[number];

export interface OpeningHours {
  /** Message key of the label shown on the page: home.hours.<id> ("Lunes a viernes"). */
  id: string;
  days: readonly DayKey[];
  /** 24 h "HH:MM", local time. "00:00" as closing time means midnight. */
  opens: string;
  closes: string;
}

export interface Restaurant {
  /** schema.org type. */
  type: "Restaurant";
  name: string;
  /** Page that represents the restaurant. */
  path: AppPathname;
  /** Photo for JSON-LD, inside public/ (the hero photo shown on its page). */
  image: string;
  telephone: {
    /** As written on the page and on the Google Business Profile. */
    display: string;
    /** E.164, for tel: links and JSON-LD. */
    e164: string;
  };
  email: string;
  address: {
    streetAddress: string;
    postalCode: string;
    addressLocality: string;
    addressRegion: string;
    /** ISO 3166-1 alpha-2. */
    addressCountry: string;
  };
  geo: { latitude: number; longitude: number };
  hours: readonly OpeningHours[];
  servesCuisine: Record<Locale, string>;
}

export const restaurant: Restaurant = {
  type: "Restaurant",
  name: SITE_NAME,
  path: "/",
  image: photo("pulpo").src,
  telephone: { display: "916 41 93 64", e164: "+34916419364" },
  email: "rochedelasislas@gmail.com",
  address: {
    streetAddress: "C. Milán, 2",
    postalCode: "28922",
    addressLocality: "Alcorcón",
    addressRegion: "Madrid",
    addressCountry: "ES",
  },
  // The place pin of the Google Maps link above.
  geo: { latitude: 40.3467086, longitude: -3.8397318 },
  hours: [
    { id: "weekdays", days: DAY_KEYS.slice(0, 5), opens: "08:00", closes: "00:00" },
    { id: "weekend", days: DAY_KEYS.slice(5), opens: "09:00", closes: "00:00" },
  ],
  servesCuisine: { es: "Española", en: "Spanish" },
};

// Legal entity behind the website (aviso legal, privacy policy). Copied
// verbatim from the previous site's aviso legal: the phone, email and address
// do not match the restaurant's and may come from another project, so the
// owner must confirm them before they are corrected.
// TODO(cliente): datos pendientes de confirmar por el propietario
export const legal = {
  company: "ROCHE DE LAS ISLAS SL",
  taxId: "B56470388",
  registeredAddress: "Calle del General Diaz Porlier 38 28001, Madrid",
  phone: "620788877",
  email: "chikinspain@gmail.com",
} as const;
